openapi: 3.0.0
info:
  title: Tax Rates & Zones
  version: ''
  description: You can use this API to manage manual tax rates and zones.
servers:
  - url: api.bigcommerce.com
paths:
  '/stores/{store_hash}/v3/tax/zones':
    get:
      tags:
        - Tax Zones
      summary: Get Tax Zones
      description: 'Retrieve a selection of tax zones when you provide a list of tax zone IDs. Otherwise, retrieve all tax zones defined on the store.'
      operationId: get-tax-zones
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for a store.
        - name: 'id:in'
          in: query
          example: '12,34,56'
          schema:
            type: string
          description: Filter by tax zone `id`. Use a comma-separated list of IDs for multiple tax zones.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tax_Zone'
                  meta:
                    type: object
    put:
      tags:
        - Tax Zones
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for a store.
      summary: Update Tax Zones
      description: Update one or more tax zones. Only the tax zone `id` field is required. Fields unspecified by the request will retain their current state.
      operationId: update-tax-zones
      requestBody:
        $ref: '#/components/requestBodies/Tax_ZoneArray'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tax_Zone'
                  meta:
                    type: object
    post:
      tags:
        - Tax Zones
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for a store.
      summary: Create Tax Zones
      description: |-
        Create one or more tax zones.

        <!-- theme:info -->
        > You cannot create a [default tax zone](/api-docs/store-management/tax/tax-rates-and-zones#default-tax-zone).
      operationId: create-tax-zones
      requestBody:
        $ref: '#/components/requestBodies/Tax_ZoneArrayPOST'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tax_Zone'
                  meta:
                    type: object
    delete:
      tags:
        - Tax Zones
      summary: Delete Tax Zones
      description: Delete one or more tax zones. Deleting a tax zone removes all associated tax rates.
      operationId: delete-tax-zones
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for a store.
        - name: 'id:in'
          in: query
          example: '12,34,56'
          schema:
            type: string
          description: Filter by tax zone `id`. Use a comma-separated list of IDs for multiple tax zones.
          required: true
      responses:
        '204':
          description: No Content
  '/stores/{store_hash}/v3/tax/rates':
    get:
      tags:
        - Tax Rates
      summary: Get Tax Rates
      description: Retrieve a list of tax rates.
      operationId: get-tax-rates
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
          description: Unique identifer for a store.
        - name: 'tax_zone_id:in'
          in: query
          example: '12,34,56'
          schema:
            type: string
          description: Filter by tax zone `id`. Use comma-separated list of IDs for multiple tax zones.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tax_Rate'
                  meta:
                    type: string
    put:
      tags:
        - Tax Rates
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for a store.
      summary: Update Tax Rates
      description: Update one or more tax rates. Only the tax rate `id` field is required. Fields unspecified by the request will retain their current state.
      operationId: update-tax-rates
      requestBody:
        $ref: '#/components/requestBodies/Tax_RateArray'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tax_Rate'
                  meta:
                    type: object
    post:
      tags:
        - Tax Rates
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for a store.
      summary: Create Tax Rates
      description: Create one or more tax rates. Tax rates must be associated with a `tax_zone_id`.
      operationId: create-tax-rates
      requestBody:
        $ref: '#/components/requestBodies/Tax_RateArrayPOST'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tax_Rate'
                  meta:
                    type: object
    delete:
      tags:
        - Tax Rates
      summary: Delete Tax Rates
      description: Delete one or more tax rates.
      operationId: delete-tax-rates
      parameters:
        - name: store_hash
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for a store.
        - name: 'id:in'
          in: query
          example: '12,34,56'
          schema:
            type: string
          description: Filter by tax rate `id`. Use comma-separated list of IDs for multiple tax rates.
          required: true
      responses:
        '204':
          description: No Content
components:
  requestBodies:
    Tax_RateArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Tax_Rate'
      required: true
    Tax_RateArrayPOST:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Tax_RatePOST'
      required: true
    Tax_ZoneArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Tax_Zone'
      required: true
    Tax_ZoneArrayPOST:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Tax_ZonePOST'
      required: true
  securitySchemes:
    API_Key:
      type: apiKey
      name: X-Auth-Token
      in: header
      description: |-
        ### OAuth Scopes
        |  **UI Name** | **Permission** | **Parameter** |
        | --- | --- | --- |
        |  Information & Settings | modify | `store_v2_information` |
        |  Information & Settings | read-only | `store_v2_information_read_only` |

        ### Headers

        |Header|Parameter|Description|
        |-|-|-|
        |`X-Auth-Token`|`access_token`|Obtained by creating an API account or installing an app in a BigCommerce control panel.|

        For more information on authenticating BigCommerce APIs, see [Authentication](/api-docs/getting-started/authentication).
  schemas:
    Tax_Zone:
      type: object
      properties:
        id:
          type: integer
          description: 'Tax Zone ID. Internal identifier used to get, update, or delete a specific tax zone.'
        name:
          type: string
          description: The human-readable name for this tax zone. The name displays on the merchant's control panel.
          example: Australia
        enabled:
          type: boolean
          description: Indicates whether a tax zone is enabled. Tax operations are only for enabled zones.
          default: true
        price_display_settings:
          type: object
          description: Settings that describe how a store displays prices to shoppers matched with this tax zone.
          properties:
            show_inclusive:
              type: boolean
              description: Indicates whether to show prices as tax inclusive or tax exclusive to shoppers matched with this tax zone.
            show_both_on_detail_view:
              type: boolean
              description: Indicates whether to show both tax inclusive and tax exclusive prices when viewing product detail (e.g. product pages). This view applies to shoppers matched with this tax zone.
            show_both_on_list_view:
              type: boolean
              description: Indicates whether to show both tax inclusive and tax exclusive prices when viewing a list of products (e.g. category and brand pages). This view applies to shoppers matched with this tax zone.
        shopper_target_settings:
          type: object
          description: Settings that describe which shoppers match this tax zone. A shopper will be matched with the most appropriate target. The default tax zone does not have any shopper target settings, as this zone applies to all shoppers that are unable to be matched with another tax zone.
          properties:
            customer_groups:
              type: array
              description: One or more customer groups that a tax zone targets. Empty array if zone applies to all customers.
              items:
                type: integer
            locations:
              type: array
              description: A tax zone may target shoppers in one or more locations.
              items:
                type: object
                properties:
                  country_code:
                    type: string
                    example: AU
                    description: 'Two-letter ISO 3166-1 country code'
                  subdivision_codes:
                    type: array
                    example:
                      - NSW
                      - QLD
                    description: 'Three-letter ISO 3166-2 subdivision code'
                    items:
                      type: string
                  postal_codes:
                    type: array
                    example:
                      - '2234'
                      - '2170'
                    items:
                      type: string
    Tax_ZonePOST:
      type: object
      description: ''
      properties:
        name:
          type: string
          description: The human-readable name for this tax zone. The name displays on the merchant's control panel.
          example: Australia
        enabled:
          type: boolean
          description: Indicates whether a tax zone is enabled. Tax operations are only for enabled zones.
          default: true
        price_display_settings:
          type: object
          description: Settings that describe how a store displays prices to shoppers matched with this tax zone.
          properties:
            show_inclusive:
              type: boolean
              description: Indicates whether to show prices as tax inclusive or tax exclusive to shoppers matched with this tax zone.
            show_both_on_detail_view:
              type: boolean
              description: Indicates whether to show both tax inclusive and tax exclusive prices when viewing product detail (e.g. product pages). This view applies to shoppers matched with this tax zone.
            show_both_on_list_view:
              type: boolean
              description: Indicates whether to show both tax inclusive and tax exclusive prices when viewing a list of products (e.g. category and brand pages). This view applies to shoppers matched with this tax zone.
          required:
            - show_inclusive
        shopper_target_settings:
          type: object
          description: Settings that describe which shoppers match with this tax zone and illustrate the most appropriate target for each shopper.
          properties:
            customer_groups:
              type: array
              description: One or more customer groups that a tax zone targets. Empty array if zone applies to all customers.
              items:
                type: integer
            locations:
              type: array
              description: A tax zone may target shoppers in one or more locations.
              items:
                type: object
                properties:
                  country_code:
                    type: string
                    example: AU
                    description: 'Two-letter ISO 3166-1 country code'
                  subdivision_codes:
                    type: array
                    example:
                      - NSW
                      - QLD
                    description: 'Three-letter ISO 3166-2 subdivision code'
                    items:
                      type: string
                  postal_codes:
                    type: array
                    example:
                      - '2234'
                      - '2170'
                    items:
                      type: string
          required:
            - locations
      required:
        - name
    Tax_Rate:
      type: object
      properties:
        id:
          type: integer
          description: Tax Rate ID. Internal identifier to update and delete a specific tax rate.
          example: 3
        tax_zone_id:
          type: integer
          description: ID of an associated tax zone. You must associate a tax rate with a tax zone.
          example: 2
        name:
          type: string
          description: 'The human-readable name for this tax zone. The name displays on the merchant's control panel and to shoppers, depending on store tax settings.'
          example: Sales Tax
        enabled:
          type: boolean
          description: Indicates whether a tax rate is enabled. Tax operations are only for enabled zones.
          default: true
        priority:
          type: integer
          description: 'Allows for compounding tax rates, common in certain jurisdictions.'
          default: 1
        class_rates:
          type: array
          description: Tax rates for tax classes. You must assign at least one tax rate for each tax class defined on a store.
          items:
            type: object
            properties:
              rate:
                type: number
                description: The tax rate that will be applied to the items in a tax class.
                example: 5
              tax_class_id:
                type: integer
                description: ID of a tax class. Each rate must be associated to a tax class. The rate will apply to all items associated with this tax class.
                example: 1
    Tax_RatePOST:
      type: object
      properties:
        tax_zone_id:
          type: integer
          description: ID of an associated tax zone. You must associate a tax rate with a tax zone.
          example: 2
        name:
          type: string
          description: 'The human-readable name for this tax zone. The name displays on the merchant's control panel and to shoppers, depending on store tax settings.'
          example: Sales Tax
        enabled:
          type: boolean
          description: Indicates whether a tax rate is enabled. Tax operations are only for enabled zones.
          default: true
        priority:
          type: integer
          description: 'Allows for compounding tax rates, common in certain jurisdictions.'
          default: 1
        class_rates:
          type: array
          description: Tax rates for tax classes. You must assign at least one tax rate for each tax class defined on a store.
          items:
            type: object
            properties:
              rate:
                type: number
                description: The tax rate that you apply to the items in a tax class.
                example: 5
              tax_class_id:
                type: integer
                description: ID of a tax class. You must associate a tax rate with a tax class. The rate will apply to all items associated with this tax class.
                example: 1
            required:
              - rate
              - tax_class_id
      required:
        - tax_zone_id
        - name
        - class_rates
security:
  - API_Key: []
tags:
  - name: Tax Zones
  - name: Tax Rates
